module DcmsApp
{
  interface Dcms
  {
	  	string sayHello();
	  	
	  	string createTRecord(in string teacher);
	
		string createSRecord(in string student);
	
		string getRecordCount();
	
		string editRecord(in string recordID, in string fieldname, in string newvalue);
		
		string editRecordForCourses(in string recordID, in string fieldName, in string newValue);
			
	  	oneway void shutdown();
  };
};
