package DcmsApp;


/**
* DcmsApp/DcmsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Monday, June 11, 2018 9:38:56 o'clock PM EDT
*/

public interface DcmsOperations 
{
  String sayHello ();
  void shutdown ();
} // interface DcmsOperations
