package DcmsApp;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLInterfaces/Dcms.idl
* Saturday, 16 June, 2018 9:30:17 PM EDT
*/

public interface Dcms extends DcmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
