package DcmsApp;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLInterfaces/DCMS.idl
* Tuesday, June 12, 2018 12:13:39 o'clock AM EDT
*/

public interface Dcms extends DcmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
