package DcmsApp;


/**
* DcmsApp/DcmsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/akhila/Documents/EE_workspace/DCMS_2/src/IDLInterfaces/Dcms.idl
* Wednesday, 13 June, 2018 3:49:15 AM EDT
*/

public interface DcmsOperations 
{
  String sayHello ();
  String createTRecord (String teacher);
  String createSRecord (String student);
  String getRecordCount ();
  String editRecord (String recordID, String fieldname, String newvalue);
  String transferRecord (String managerID, String recordID, String location);
  String editRecordForCourses (String recordID, String fieldName, String newValue);
  void shutdown ();
} // interface DcmsOperations
