package DcmsApp;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dcms.idl
* Wednesday, 13 June, 2018 12:31:24 PM EDT
*/

public interface Dcms extends DcmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
