package DcmsApp;


/**
* DcmsApp/DcmsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLInterfaces/Dcms.idl
* Saturday, June 16, 2018 11:55:42 o'clock AM EDT
*/

public interface DcmsOperations 
{
  String createTRecord (String teacher);
  String createSRecord (String student);
  String getRecordCount ();
  String editRecord (String managerID, String recordID, String fieldname, String newvalue);
  String transferRecord (String managerID, String recordID, String location);
  void shutdown ();
} // interface DcmsOperations
