package DcmsApp;


/**
* DcmsApp/DcmsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Monday, June 11, 2018 9:38:56 o'clock PM EDT
*/

public abstract class DcmsPOA extends org.omg.PortableServer.Servant
 implements DcmsApp.DcmsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DcmsApp/Dcms/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DcmsApp/Dcms/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DcmsApp/Dcms:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dcms _this() 
  {
    return DcmsHelper.narrow(
    super._this_object());
  }

  public Dcms _this(org.omg.CORBA.ORB orb) 
  {
    return DcmsHelper.narrow(
    super._this_object(orb));
  }


} // class DcmsPOA
