package DcmsApp;


/**
* DcmsApp/Dcms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Wednesday, June 13, 2018 4:36:26 PM EDT
*/

public interface Dcms extends DcmsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dcms
